language: go
go:
  - 1.10.x
  - master
os:
  - linux
  - osx
dist: trusty
sudo: false
install: true
script:
  - go get -t -v github.com/fsnotify/fsnotify
  - go get -t -v github.com/spf13/viper
  - go get -t -v github.com/hashicorp/hcl
  - go get -t -v github.com/magiconair/properties
  - go get -t -v github.com/mitchellh/mapstructure
  - go get -t -v github.com/pelletier/go-toml
  - go get -t -v github.com/spf13/afero
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test